import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */


export const products = [
  {
    _id: uuid(),
    title: "Mango Tropical Cake",
    image:mango1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/mango1_fwaa0l.webp",
    ratings: {
      rate:"4.5",
      count:"985"
    },
    price: "499",
    originalPrice: "579",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Cake",
    desc:"The Mango Tropical Cake is an ideal dessert for mango lovers and those seeking a unique twist on traditional cakes. It is perfect for special occasions, celebrations, or simply as a decadent treat to savor any time of the year. (6 serving,169 calories each, protein-3 grams each, carbs-33 grams each)",
  },
  {
    _id: uuid(),
    title: "Butterscotch Overloaded Cake",
    image:butter1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/butter1_zjd04q.jpg",
    ratings: {
      rate:"4.1",
      count:"622"
    },
    price: "799",
    originalPrice: "929",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: true,
    priceCategory: "under1000",
    type:"Cake",
    desc:"Good old butterscotch cake - just overload of it to give you an unmatched taste. Best choice for Birthday cake or Anniversary cake. (Vanilla Sponge + Butterscotch nuts + Butterscotch crush) (6 Serving, 152 calories each, protein-3g each, carbs-29g each)",
  },
  {
    _id: uuid(),
    title: "Rasmalai Cake",
    image:ras1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/rasmalai-cake_gfbhfb.jpg",
    ratings: {
      rate:"3.9",
      count:"234"
    },
    price: "499",
    originalPrice: "579",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "under500",
    type:"Cake",
    desc:"Yummy Indian fusion Rasmalai cake - a blend of traditional indian Rasmalai sweet and western dessert. [Vanilla+Rasmalai+Kesar milk] ( 6 Serving , 211 calories each, Protein-4g, Carbs-31g each) ",
  },
  {
    _id: uuid(),
    title: "Chocolate Truffle Cake",
    image:mango1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/chocolate-truffle-cake_gaygcj.jpg",
    ratings: {
      rate:"4.7",
      count:"2.1k"
    },
    price: "489",
    originalPrice: "679",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Cake",
    desc:"If it were easy to resist, it would not be called chocolate cake. Try our bestseller to taste real freshness. Best choice for Birthday cake or Anniversary cake. [ Chocolate Sponge + Truffle + Chocolate layering] (6 Serving, 401 calories each, protein-7g each, carbs- 53g each)",
  },
  {
    _id: uuid(),
    title: "Jungle Safari Fondant Cake",
    image:jungle1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/jungle-fondant-cake_japot9.jpg",
    ratings: {
      rate:"4.2",
      count:"566"
    },
    price: "1499",
    originalPrice: "1799",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "under1500",
    type:"Cake",
    desc:"Invite some wilderness in your birthday party by ordering this jungle safari fondant theme cake, this cake is filled with animals which cherishes kids and greenery around signifies the nature of forest. You can choose the flavor which you like most. All our cakes are made fresh and with love, with No added preservatives, all-natural, and best-quality ingredients safe for children and adults.",
  },
  {
    _id: uuid(),
    title: "Red Velvet Egg Cake",
    image:red1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/red-velvet-egg-cake_m0v2hi.jpg",
    ratings: {
      rate:"4.0",
      count:"1.67k"
    },
    price: "689",
    originalPrice: "899",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "under1000",
    type:"Cake",
    desc:"Preparation starts after receiving the order. No storage. Scrumptious and tempting, creamy red velvet cake with the taste of cocoa and sugar. (6 Serving, 383 calories each, protein-6g each, carbs-47g each)",
  },
  {
    _id: uuid(),
    title: "Strawberry Cheesecake",
    image:straw1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/strawberry-cheesecake-500gm-_tqhdzv.jpg",
    ratings: {
      rate:"4.9",
      count:"979"
    },
    price: "979",
    originalPrice: "1129",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: true,
    priceCategory: "under1000",
    type:"Cake",
    desc:"Bite into our smooth, rich, fresh, and dense texture of cheesecake and Strawberry . We stand by our promise, of sweeter celebrations with CakeZone. (4 Serving, 567 calories each, protein - 6g each, carbs-53g each)",
  },
  {
    _id: uuid(),
    title: "Mango Fruit Eggless Cake",
    image:mango2,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/mango-fruit-eggless-cake_dpawsn.jpg",
    ratings: {
      rate:"4.3",
      count:"2.3k"
    },
    price: "489",
    originalPrice: "579",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Cake",
    desc:"Bite into artisanal Mango fruit cake topped with tasty, flavored mango filling on top and layered vanilla sponge, our fresh cake made right after the order is placed. We stand by our promise of delivering sweeter celebrations. [ Vanilla Sponge + Mango filling + Mango Crush + Cream] (6 serving, 321 Calories each, protein-6g each, Carbs-56g each",
  },
  {
    _id: uuid(),
    title: "French Blueberry Cheese Cake",
    image:blue1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/french-blueberry-cheese-cake-500gm-_dhxiff.jpg",
    ratings: {
      rate:"4.2",
      count:"147"
    },
    price: "989",
    originalPrice: "1139",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: false,
    priceCategory: "under1000",
    type:"Cake",
    desc:"The richness of fresh cheesecake is topped with premium blueberry fruit filling. (4 Serving, 521 calories each, protein-6g each, carbs-40g each) ",
  },
  {
    _id: uuid(),
    title: "Black Forest Eggless Cake",
    image:black1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684828631/cakefactory/cakes/black-forest-eggless-cake_ywqqug.jpg",
    ratings: {
      rate:"4.7",
      count:"2.3k"
    },
    price: "499",
    originalPrice: "579",
    categoryName: "Cakes",
    isInStock: true,
    weight: "1 kg",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Cake",
    desc:"Several layers of chocolate cake, with cherry filling, with lashings of whipped cream between each layer. The cake is then decorated with piped, whipped cream, maraschino cherries, and chocolate shavings. We stand by our promise, sweeter celebrations with CakeZone. (Chocolate Sponge + Cherry + Chocolate Flakes) ( 6 Serving, 327 calories each, protein-5g each, carbs-56g each)",
  },

  {
    _id: uuid(),
    title: "Chocolote Muffin",
    image:muffin1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684830885/cakefactory/muffins/muffin1-choco_zz0cxs.webp",
    ratings: {
      rate:"4.1",
      count:"128"
    },
    price: "99",
    originalPrice: "129",
    categoryName: "Muffins",
    isInStock: true,
    weight: "80gm",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Muffin",
    desc:"This delicious Chocolate Muffin made with chocolate chips and rich ganache filling is what chocolatey dreams are made of.",
  },
  {
    _id: uuid(),
    title: "Red Velvet Muffin",
    image:muffin2,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684830885/cakefactory/muffins/muffin2_zmisrt.webp",
    ratings: {
      rate:"4.8",
      count:"612"
    },
    price: "99",
    originalPrice: "129",
    categoryName: "Muffins",
    isInStock: true,
    weight: "80gm",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Muffins",
    desc:"Our Red Velvet muffin made with soft sponge filled with delicious cream cheese is sure to give a velvety touch to your tastebuds.",
  },
  {
    _id: uuid(),
    title: "Blueberry Muffin",
    image:muffin3,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684830885/cakefactory/muffins/muffin3-blue_qd50gq.webp",
    ratings: {
      rate:"4.3",
      count:"29"
    },
    price: "99",
    originalPrice: "129",
    categoryName: "Muffins",
    isInStock: true,
    weight: "80gm",
    isBestSeller: false,
    priceCategory: "under500",
    type:"Muffins",
    desc:"Our delicious muffins made with fresh blueberries are an absolute delight in every bite. Must try!",
  },
  {
    _id: uuid(),
    title: "Hazlenut Muffin",
    image:muffin4,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684830885/cakefactory/muffins/muffin4-hazlenut_ebmwvh.webp",
    ratings: {
      rate:"4.0",
      count:"199"
    },
    price: "99",
    originalPrice: "129",
    categoryName: "Muffins",
    isInStock: true,
    weight: "80gm",
    isBestSeller: false,
    priceCategory: "under500",
    type:"Muffins",
    desc:"A nutty affair you wont want to miss out on. Rich chocolatey muffin with delicious Nutella filling.",
  },
  {
    _id: uuid(),
    title: "Dark Fantasy Muffin",
    image:muffin5,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684830885/cakefactory/muffins/muffin5-darkfant_up0yux.webp ",
    ratings: {
      rate:"4.3",
      count:"322"
    },
    price: "99",
    originalPrice: "129",
    categoryName: "Muffins",
    isInStock: true,
    weight: "80gm",
    isBestSeller: false,
    priceCategory: "under500",
    type:"Muffins",
    desc:"Coated with love and filled with lots of chocolate. Thats what our chocolate dark fantasy muffins are about!",
  },

  {
    _id: uuid(),
    title: "Strawberry Cheesecake",
    image:pastry1,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684833624/cakefactory/muffins/pastry1-strawberry_ipi1tg.webp",
    ratings: {
      rate:"4.4",
      count:"722"
    },
    price: "189",
    originalPrice: "229",
    categoryName: "Muffins and Pastries",
    isInStock: true,
    weight: "180gm",
    isBestSeller: false,
    priceCategory: "under500",
    type:"Pastry",
    desc:"Delectable cheesecake made with fresh strawberries and rich cream cheese is sure to make you fall in love berry much. Try now!",
  },
  {
    _id: uuid(),
    title: "Blueberry Cheesecake",
    image:pastry2,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684833625/cakefactory/muffins/pastry2-blueberry_nhvcrt.webp",
    ratings: {
      rate:"4.9",
      count:"2.5k"
    },
    price: "189",
    originalPrice: "229",
    categoryName: "Muffins and Pastries",
    isInStock: true,
    weight: "180gm",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Pastry",
    desc:"The combination of delicious cream cheese and fresh blueberries is what makes our Blueberry cheesecake stand apart. Try now!",
  },
  {
    _id: uuid(),
    title: "Rich Red Velvet Pastry",
    image:pastry3,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684833625/cakefactory/muffins/pastry3-red-velvet_uoqkba.webp",
    ratings: {
      rate:"4.5",
      count:"1.2k"
    },
    price: "159",
    originalPrice: "239",
    categoryName: "Muffins and Pastries",
    isInStock: true,
    weight: "180gm",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Pastry",
    desc:"Rich and moist Red Velvet cake layered with fresh cream cheese makes our Red Velvet pastry difficult to share. Youll think twice too",
  },
  {
    _id: uuid(),
    title: "Chocolate Truffle Pastry",
    image:pastry4,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684833625/cakefactory/muffins/pastry4-choc-truffle2_ts1jsz.jpg",
    ratings: {
      rate:"4.3",
      count:"565"
    },
    price: "149",
    originalPrice: "179",
    categoryName: "Muffins and Pastries",
    isInStock: true,
    weight: "180gm",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Pastry",
    desc:"(Eggless) Layers of soft chocolate sponge and dense but silky-smooth chocolate ganache make this cake a decadent celebration.",
  },
  {
    _id: uuid(),
    title: "Mango Cheesecake",
    image:pastry5,
    imageUrl:"https://res.cloudinary.com/darl8idou/image/upload/v1684833624/cakefactory/muffins/pastry5-mango_tvclwg.webp",
    ratings: {
      rate:"4.1",
      count:"233"
    },
    price: "129",
    originalPrice: "159",
    categoryName: "Muffins and Pastries",
    isInStock: true,
    weight: "180gm",
    isBestSeller: true,
    priceCategory: "under500",
    type:"Pastry",
    desc:"(Eggless) This New York Style Mango Cheesecake, made with premium quality cream cheese and a crust infused with delicious mango flavor, is every dessert lovers delight!",
  },
];

